// Template assets for `plune init` (T03). Kept as TS string constants rather than separate
// `.tpl` files so they survive bundling (tsup) without runtime asset-path resolution.
//
// SECURITY (constitution §4, NFR-5): `.env.example` holds ONLY placeholders — `plune init`
// never writes a populated `.env`. The example dataset uses harmless sample prompts (no PII).

import * as fs from 'node:fs';
import * as path from 'node:path';

/** Committed sample env file. Users copy it to `.env` (gitignored) and fill in real keys. */
export const ENV_EXAMPLE_TPL = `# Copy this file to .env and replace the placeholders with your real keys.
# .env is gitignored; .env.example is safe to commit.
# Plune reads whichever key matches your configured provider.
ANTHROPIC_API_KEY=YOUR_ANTHROPIC_API_KEY_HERE
OPENAI_API_KEY=YOUR_OPENAI_API_KEY_HERE
OPENROUTER_API_KEY=YOUR_OPENROUTER_API_KEY_HERE
`;

/** Starter dataset (JSONL, one row per line) matching the DatasetRow shape `{ vars, expected? }`. */
export const EXAMPLE_JSONL_TPL = `{"vars":{"question":"What is 2 + 2?"},"expected":"4"}
{"vars":{"question":"What is the capital of France?"},"expected":"Paris"}
{"vars":{"question":"Reply with the single word: hello"},"expected":"hello"}
`;

/**
 * Default plune.yaml for `plune init --yes` (non-interactive). A commented, valid config that
 * references the example dataset, so a freshly-scaffolded project runs without hand-editing.
 * (The interactive wizard builds its own plune.yaml from the user's answers.)
 */
export const PLUNE_YAML_TPL = `# Plune configuration — generated by \`plune init --yes\`.
#
# version  — config schema version (always 1 in v0.1).
# provider — which LLM backend to call: 'type' (anthropic | openai | openrouter) + 'model'.
#            The API key is read from .env (see .env.example), never stored here.
# evals    — your test cases: a prompt (with {{vars}}), a dataset, and assertions to check.
version: 1
provider:
  type: anthropic
  model: claude-3-5-sonnet-latest
evals:
  - id: example
    prompt: "Answer concisely. {{question}}"
    dataset: datasets/example.jsonl
    assertions:
      - type: contains
        value: "the"
`;

/**
 * Write a template to `<cwd>/<rel>`, creating parent directories.
 * Returns `'skipped'` (and leaves the file untouched) if it already exists and `force` is false;
 * otherwise writes the content and returns `'written'` (AC-T03 2/3).
 */
export function writeTemplateFile(
  cwd: string,
  rel: string,
  content: string,
  force: boolean,
): 'written' | 'skipped' {
  const target = path.join(cwd, rel);
  if (!force && fs.existsSync(target)) {
    return 'skipped';
  }
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, content, 'utf8');
  return 'written';
}
