import * as clack from '@clack/prompts';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { stringify } from 'yaml';
import { NonTtyError } from '../errors.js';

export async function runInitWizard(cwd: string): Promise<void> {
  if (!process.stdin.isTTY) {
    throw new NonTtyError();
  }

  clack.intro('Plune — init');

  const provider = await clack.select({
    message: 'Choose your provider:',
    options: [
      { value: 'anthropic', label: 'Anthropic (Claude)' },
      { value: 'openai', label: 'OpenAI (GPT)' },
    ],
  });

  if (clack.isCancel(provider)) {
    clack.cancel('Operation cancelled.');
    process.exit(1);
    return;
  }

  const defaultModel = provider === 'anthropic' ? 'claude-3-opus' : 'gpt-4o';

  const model = await clack.text({
    message: 'Model name:',
    defaultValue: defaultModel,
    placeholder: defaultModel,
  });

  if (clack.isCancel(model)) {
    clack.cancel('Operation cancelled.');
    process.exit(1);
    return;
  }

  const dataset = await clack.text({
    message: 'Dataset path (JSONL):',
    placeholder: 'data/evals.jsonl',
  });

  if (clack.isCancel(dataset)) {
    clack.cancel('Operation cancelled.');
    process.exit(1);
    return;
  }

  const outputPath = path.join(cwd, 'plune.yaml');

  if (fs.existsSync(outputPath)) {
    const overwrite = await clack.confirm({
      message: 'plune.yaml already exists. Overwrite?',
    });

    if (clack.isCancel(overwrite)) {
      clack.cancel('Operation cancelled.');
      process.exit(1);
      return;
    }

    if (!overwrite) {
      clack.outro('No changes made.');
      return;
    }
  }

  const config = {
    version: 1,
    provider: {
      type: provider as string,
      model: model as string,
    },
    evals: [
      {
        id: 'example-eval',
        prompt: 'Replace this with your actual prompt',
        dataset: dataset as string,
        assertions: [{ type: 'contains', value: 'expected output' }],
      },
    ],
  };

  // Explanatory header so a hand-editing user understands each field (AC-T03.5).
  const header = `# Plune configuration — generated by \`plune init\`.
#
# version  — config schema version (always 1 in v0.1).
# provider — which LLM backend to call: 'type' + 'model'. The API key is read from .env
#            (see .env.example), never stored here.
# evals    — your test cases. Each has a prompt, a dataset of variables, and assertions
#            that must hold for the model's output.
`;

  const spin = clack.spinner();
  spin.start('Writing plune.yaml…');
  fs.writeFileSync(outputPath, header + '\n' + stringify(config), 'utf8');
  spin.stop('plune.yaml created!');

  clack.outro('Done! Run `plune run` to execute your evaluations.');
}
